### ISSUE TITLE
Modernizr Support

### ISSUE THREAD

**Issue by Fastspot** [Fastspot/Boilerplate#1]
Part of the boiler plate is moving to Modernizr for feature detection. This will allows us to utilize the '.not-feature' classes in our styles, however I don't think we need to include every test they offer. We normally don't need to worry about stuff like box-shadow not being available so I would like some input on what should be included in our custom build. 

Sidebar: I was reading that the new version is slated to have a grunt build process where this could be automated on a per-project basis. However until that version is released we need a more generic a custom build, which could then be overwritten if the project requires extra tests. 

Right now I plan to include:

-Flexbox
-Flexbox legacy
-multiple backgrounds
-rgba
-css animations
-css columns
-css generated content
-css gradients
-css 2d & 3d transforms
-css transitions
-history api
-html5 audio & video
-svg
-touchevents

Take a look at what is offered (http://modernizr.com/download/) and let me know if you think we need to add/remove anything from this list.

**Comment by benplum** [comment]
-Added background-size to list.
-Including yepnope (w/ modernizr.load) to help polyfill unsupported features (like background-size w/ Wallpaper fallback).
-Including html5shiv (instead of html5 enabler)

We'll treat this issue a living document and keep it open.

**Comment by nhall** [comment]
This issue is from three months ago so I'm probably not telling you anything you don't already know but [modernizr grunt plugin](https://github.com/Modernizr/grunt-modernizr) is available.  

It's really convenient. You pretty much just pass in the modernizr file you want to use and where the updated file should be output. Then tell it what files you want it to parse. Really it could be as simple as:

```
modernizr: {
    dist: {
        devFile: '/src/js/modernizr.js',
        outputFile: '/dist/js/modernizr.js',
        files: {
            src: [
                'src/js/{,*/}*.js',
                'src/css/{,*/}*.css',
            ]
        }
    }
},
```

Even better you can team it up with bower and use the modernizr file that you get from there. Then you completely automate the creation of your modernizr file.

**Comment by benplum** [comment]
We're actually moving to a Grunt build process so this will be very helpful. Thanks for the heads up.

**Comment by benplum** [comment]
Fixed.
